### ISSUE TITLE
Is there a functionality for convering m2 file back to their parallel corpuses?

### ISSUE THREAD

**Issue by Chhokra** [chrisjbryant/errant#19]
Datasets like FCE have been standardised into m2 formats using ERRANT. But some models take parallel corpuses as inputs - so how does one change it back to their parallel corpus format? (Reverse of what ERRANT does)

**Comment by chrisjbryant** [comment]
There is a script on the BEA 2019 shared task website to apply the edits to get the corrected text: [link](https://www.cl.cam.ac.uk/research/nl/bea2019st/data/corr_from_m2.py)

As for the original text, I just run:
`grep ^S m2_file | cut -c 3- > output.orig`

**Comment by sappy5678** [comment]
> There is a script on the BEA 2019 shared task website to apply the edits to get the corrected text: [link](https://www.cl.cam.ac.uk/research/nl/bea2019st/data/corr_from_m2.py)
> 
> As for the original text, I just run:
> `grep ^S m2_file | cut -c 3- > output.orig`

I run the code to get correct sentences from BEA2019 dev m2. But the F0.5 score is only 86.45 when I upload the correct sentences to Codalab of BEA2019.  Did I do something wrong?

The command that I run:
`python office_correct.py ~/Corpus/BEA2019/wi+locness/m2/ABCN.dev.gold.bea19.m2 -out office.gold`

**Comment by chrisjbryant** [comment]
No, that's correct. The reason is because the reference edits in Codalab were annotated by humans, while the hypothesis edits were extracted automatically with ERRANT. Consequently, even though the corrected sentences are the same, there is a mismatch between the spans of the gold and automatic edits.

You can read a bit more about this in Section 4.1 of the [ERRANT paper](https://www.aclweb.org/anthology/P17-1074.pdf) and also Appendix A.7 in the [BEA-19 shared task paper](https://www.cl.cam.ac.uk/~cjb255/papers/2019-bea19st/bea2019st.pdf).

**Comment by sappy5678** [comment]
Thank you for your detailed explanation.
