### ISSUE TITLE
Errant for Arabic language

### ISSUE THREAD

**Issue by aimanmutasem** [chrisjbryant/errant#23]
Hello :) 

Is there any way to use errant with other languages like Arabic language, and using [BERT Multi-language](https://github.com/google-research/bert/blob/master/multilingual.md) or [BPEmb](https://nlp.h-its.org/bpemb/) instead of spacy?

King regards,
Aiman Solyman

**Comment by chrisjbryant** [comment]
Hey, :)

Currently, there isn't a super straightforward way to use errant with other languages because there are some language-specific rules. Running the English pipeline nevertheless still works fairly well with some languages, but I've not tried it with Arabic. 
Also I'm not sure what you mean when you suggest using BERT or BPEmb instead of spacy, because errant requires spacy for POS tagging and parsing which the others don't do by default. 

Hope this helps!

**Comment by aimanmutasem** [comment]
Thank you, dear :) 

Unfortunately, spacy doesn't support Arabic language, so my idea is to use Arabic POS with errant.
