### ISSUE TITLE
Clarification on Spacy 2.0

### ISSUE THREAD

**Issue by sai-prasanna** [chrisjbryant/errant#5]
In the documentation you have mentioned that spacy 2.0 is less compatible with ERRANT. What is the nature of this incompatibility and any pointers on what can be done to correct for it?

**Comment by chrisjbryant** [comment]
Hey, good question, with a bit of a complicated answer!

For a long time, the coarse POS tags that spacy uses have been somewhere in between the Google Universal Tagset and the Stanford Universal Dependency Tagset. I tried to get them to standardise the tagset since before spacy v.1.0 (explosion/spaCy#191 and explosion/spaCy#593), but with no luck. Consequently, ERRANT was built on the slightly unusual tag set and I added some mappings to convert spacy tags to the Stanford one myself.

When spacy 2.0 appeared however, so did documents about annotation guidelines, including some new POS tags and parse labels; e.g. AUX and dative: (see [here](https://spacy.io/api/annotation))

This made me believe the models in spacy 2 were now trained on different pos tags and parse labels. Since ERRANT is very dependent on pos tags and, to a lesser extent, parse labels, I was worried this would mean some of the error type rules would no longer work. Consequently, I thought it safer to stick to spacy 1 just to ensure compatibility.

A further twist is that the models for spacy 2 might actually use the same labels as spacy 1, and it's just the annotation docs that are different and misleading. For example, the official spacy tag_map file that maps fine tags to coarse tags does not mention the new AUX tag at all: [tag_map.py](https://github.com/explosion/spaCy/blob/master/spacy/lang/en/tag_map.py)

Ultimately, it seemed safer to rely on spacy 1 than risk spacy 2, although it might be the case that spacy 2 works fine anyway. The current formulation of ERRANT is still faster on spacy 1 though.
