### ISSUE TITLE
U type when there is a correction

### ISSUE THREAD

**Issue by borgr** [chrisjbryant/errant#9]
Using the most up to date github clone we have found ERRANT output (e.g. on w&i as attached) sometimes categorizes an error as of  unnecessary(U:) type although it is a replacement type. 

See for example:
S The rich people will buy a car but the poor people always need to use a bus or taxi .
A 0 2|||U:DET|||Rich|||REQUIRED|||-NONE-|||0

[ABCN.dev.gold.bea19.m2.txt](https://github.com/chrisjbryant/errant/files/3782958/ABCN.dev.gold.bea19.m2.txt)

**Comment by chrisjbryant** [comment]
This one is actually by design.

Although you're right that the edit is technically a replacement of ["The rich" -> "Rich"], the main error is actually the unnecessary determiner. It's simply because the unnecessary word is also the first word in the sentence that we must also change the case of "rich". 

We thus decided to ignore the case change whenever there is a missing or unnecessary word at the start of a sentence.
